version: '3'

services:
  node:
    build: .
    env_file: .env
    ports:
      - "82:3000"
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
  bd:
    image: mariadb:latest
    env_file: .env
    volumes:
      - /mariadb/setup.sql:/docker-entrypoint-initdbd/setup.sql
      - dados_mariadb:/var/lib/mysql
   
  mongo:
    image: mongodb/mongodb-community-server:4.4.25-ubuntu2004
    env_file: .env
    volumes:
      - mongo_data:/data/db

volumes:
  dados_mariadb:
  node_modules:
  mongo_data:

